import { cn } from "@/lib/utils";
import "./globals.css";
import { Inter } from "next/font/google";
import ContextProvider from "@/components/context-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "w-full min-h-screen flex justify-center items-center flex-col"
        )}
      >
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
